feat: Support django-reversion and django-reversion-compare
unfoldadmin/django-unfold pull request #90
Opened 2023-06-26 03:05 UTC by justinqian42

Initial support for both django-reversion and django-reversion-compare plugins, to correctly style the corresponding pages

2023-06-26 03:11 UTC, justinqian42 commented
I'm trying to apply the same logic for the import-export support without touching any core codes of unfold.
To use this feature, users will need to inherit VersionAdmin and/or CompareVersionAdmin from unfold.contrib.reversion and/or unfold.contrib.reversion_compare.

The corresponding change to the manual will be submitted later after this PR is properly reviewed.

2023-09-15 12:23 UTC, PavelPancocha approved these changes
In overall great! Thank you!

Having some tests would be great, maybe do them as another tests suite with conditinal dependecis for tox?

2023-09-15 12:23 UTC, PavelPancocha commented on src/unfold/contrib/reversion/admin.py
> +        # return redirect(self.get_urls)
Unnecessary comment

2023-09-15 12:23 UTC, PavelPancocha commented on src/unfold/contrib/reversion_compare/admin.py
> +        # return redirect(self.get_urls)
Unnecessary comment

2023-11-06 14:39 UTC, PavelPancocha requested changes
@justinqian42 

I did deeper review and I found it doesn't work as expected:

- the path with `\` _backslash_ is not valid
_(I fixed that on my side for further testing)_
- Unfold media (CSS) are missing, Can be fixed by adding Unfold "ModelAdmin" as base class (I suppose, that usage should be only with "version" admin.

![image](https://github.com/unfoldadmin/django-unfold/assets/30392053/0ef2afe1-eb7a-4361-b6ec-ab0b74fd49df)

![image](https://github.com/unfoldadmin/django-unfold/assets/30392053/35897d84-20a8-4c39-8782-80c167ac337b)


Integrations tests would be great (that would test, that all media files etc. are loaded properly). Also that given pages could be displayed, as because of the broken path it didn't work properly (Django crashed).

2023-11-06 14:39 UTC, PavelPancocha commented on src/unfold/contrib/reversion/admin.py
> +    recover_list_template = "reversion\recover_list.html"
The back-slashes are wrong. Doesn't work on unix like systems!

2023-11-07 09:23 UTC, justinqian42 commented
Thank you @PavelPancocha for the feedback.
It's been a while since I submitted the PR and I almost forgot it.

To be honest, I've got very little experience with the frontend stuff and class method overwriting. Will try to fix the issues but please don't put a high expectation on me......

Will find some time.

2023-11-07 09:30 UTC, PavelPancocha commented
@justinqian42 Feel free to let me know - we look forward to using Django Unfold with reversion in ~2 months, so it would be great to make this working :)

2023-12-29 10:42 UTC, closed without merging

2025-12-29 18:27 UTC, alex-deltia commented
@lukasvinclav does the closing of this PR (and the related issue) with the "wontfix" tag mean that you won't be merging any PRs unless it's through your consulting services?